### ISSUE TITLE
Cannot use AUTOPSY. because Fw wont allowed downloads of models from server

### ISSUE THREAD

**Issue by seychelles111** [lxndrblz/forensicsim#65]
![image](https://github.com/lxndrblz/forensicsim/assets/130751272/e8081a1b-35df-43ee-bf5e-2ff9172db942)

**Comment by lxndrblz** [comment]
Hi @seychelles111,

Could you please provide me the autopsy log file?

Were you able to run the parser as a standalone executable before? Because if it doesn't work standalone the Autopsy module will also fail as it relies on the executable.

Please refrain from opening in-descriptive issues, such as the current one, in the future. To troubleshoot, I need a detailed log and not just a screenshot and a wild guess as a title.

**Comment by seychelles111** [comment]
> Were you able to run the parser as a standalone executable before? Because if it doesn't work standalone the Autopsy module will also fail as it relies on the executable.

Ofc I couldnt, because it relays on the .py ? isnt it ?

it didnt worked. never the less.

**Comment by seychelles111** [comment]
![image](https://github.com/lxndrblz/forensicsim/assets/130751272/0d9a84c4-8ae7-4636-899d-2472aa8df6af)

For the same reason, I pushed those PR 

its just really awfully intergrated 


the weird thing is that 
https://github.com/cclgroupltd/ccl_chrome_indexeddb
I can export to csv... just without the decoding thing... but whatever


@lxndrblz @xambroz 

I really need to archive my chats. 

thank you

**Comment by lxndrblz** [comment]
@seychelles111  Please try running this release:

https://github.com/lxndrblz/forensicsim/releases/tag/v0.8.0

It should solve all of your problems that you had reported so far.
