### ISSUE TITLE
[Autopsy] Failed to load ForensicIMIngestModuleFactory

### ISSUE THREAD

**Issue by itsathejoey** [lxndrblz/forensicsim#77]
I am receivng the below error when trying to add the plugin for the parser into Autopsy.

![image](https://github.com/lxndrblz/forensicsim/assets/100420299/7ffb9e55-9656-49bf-8ee2-9b86bb183f89)

**Comment by lxndrblz** [comment]
@itsathejoey Hi there, Thanks for bringing this to my attention. Would you mind sharing the autopsy log to see if there were any errors when you ran the module?

**Comment by itsathejoey** [comment]
[autopsy.log.0.txt](https://github.com/lxndrblz/forensicsim/files/14893758/autopsy.log.0.txt)

Yes it looks like the log states the same error.

**Comment by kyleEeeEEeeee** [comment]
I'm getting the same thing

**Comment by itsathejoey** [comment]
Has there been any fix to this?

**Comment by lxndrblz** [comment]
Hi, everyone thanks for reporting this issue. I will have to investigate what is causing it.

**Comment by minit01** [comment]
Same issue on my side - is there anything we can do to support you in getting a fix soon ? :)

**Comment by 4ensicDev** [comment]
This error is caused by the `self.log()` methods that write log information into the log file.  For some reason the author used an unsupported argument format for some log message function.  To resolve the issue do the following:

1. Put the parser in the proper plug-in directory within your Autopsy installation
2. Open Forensicsim_parser.py in your preferred editor
3. Search for the string 'f"'. There should be 6 hits.
4. Update the code arguments for the 'self.log()' function for each hit as follows:

example (line #769):
`self.log(
     Level.INFO,
     f"Found {directories_to_process} {directory} directories to process.",
)`
to
`self.log(
     Level.INFO,
     "Found {} {} directories to process.".format(directories_to_process,directory),
)`

4. Repeat the format changes for each of the respective search hits
5. Save the python script
6. Run the parser

Note: While this resolves the error message listed above while loading the plugin, I noticed the actual parsing of Teams messages is still failing on newer Teams versions.  I have identified the following issues on newer Teams versions:

1. The ms_teams_parser.exe is failing because it is missing the export of the "blob" folder which is 'https_teams.microsoft.com_0.indexeddb.blob'
2. If the "blob" folder is exported, and the ms_teams_parser.exe is executed manually with the switches '--filepath', '--outputpath' and '--blobpath' on the exported Teams folders ".blob" and ".leveldb" the resulting .json file is not recording the actual leveldb file name from where the records were extracted from. The json only records the path in the 'origin_file' attribute in the .json file.  This will cause the parser to fail staging the records in Autopsy.

Trying to resolve the ms_teams_parser.exe issue for a case myself.

Hope this "workaround" will still work for other Teams versions.

**Comment by lxndrblz** [comment]
@4ensicDev Thanks for your analysis. I will check it out and report back.
